dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide1530 password 'decide1530'"
  - psql -U postgres -c "create database decide900 owner decide1530"
  - psql -U postgres -c "ALTER USER decide1530 CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - cp travis_local_settings.py local_settings.py
  - coverage run --branch --source=. ./manage.py test --keepdb 
  - coverage xml
  - python-codacy-coverage -r coverage.xml
branches:
  only:
    - master

deploy:
  provider: heroku
  app: jose-egc-examen1530
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
